name: Add package to release
on:
  release:
    types: [published]

env:
  version: 2.0.1

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Clone
      uses: actions/checkout@v3
    - name: Zip
      run: |
        cd ..
        zip -r archive.zip ./hazard-stripes -x "*/.git/*" "*/.github/*" "*/assets/*" "*/.editorconfig" "*/.gitignore"
    - name: Release
      uses: svenstaro/upload-release-action@2.9.0
      with:
        file: ../archive.zip
        asset_name: hazard-stripes_${{ env.version }}.zip
